# """
# LLM Synthesis — Grounded Agricultural Advisory Generation
# =========================================================
# Calls the Claude API with a structured prompt that forces every claim
# in the output to be cited against a retrieved source passage.

# The grounded JSON output schema is the technical foundation for the
# RAGAS faithfulness metric used in the CI evaluation gate.
# """

# import json
# from dataclasses import dataclass
# from typing import Optional

# import anthropic

# from retrieval import RetrievedChunk

# CLAUDE_MODEL = "claude-sonnet-4-6"
# MAX_TOKENS   = 2048


# # ── Output Data Models ─────────────────────────────────────────────────────────

# @dataclass
# class CitedClaim:
#     """A factual claim with 0-indexed pointers into the retrieved_chunks list."""
#     claim:          str
#     source_indices: list[int]


# @dataclass
# class AdvisoryReport:
#     """Fully structured advisory report returned to the API layer."""
#     caption:                  str
#     summary:                  str
#     diagnosis:                str
#     treatment_recommendations: list[str]
#     cited_claims:             list[CitedClaim]
#     confidence_level:         str              # 'High' | 'Medium' | 'Low'
#     follow_up_actions:        list[str]
#     raw_sources:              list[RetrievedChunk]


# # ── System Prompt ──────────────────────────────────────────────────────────────

# SYSTEM_PROMPT = """You are an expert agricultural plant pathologist and certified agronomist.

# You will receive:
#   1. A visual description of a crop image (generated by a computer vision model).
#   2. Retrieved knowledge base passages, each labelled [Source N].
#   3. GPS location and observation date context.

# Your task is to generate a structured JSON advisory report.

# STRICT GROUNDING RULES:
#   - Every factual claim in diagnosis or treatment MUST cite at least one source index.
#   - Do NOT introduce any information not present in the retrieved passages.
#   - If the retrieved evidence is insufficient for a high-confidence diagnosis,
#     set confidence_level to 'Low' and state the limitation clearly in the diagnosis field.
#   - source_indices must be valid 0-based integers from the provided context.

# OUTPUT FORMAT — return ONLY the JSON object below, no markdown fences, no preamble:
# {
#   "summary": "<one sentence overview>",
#   "diagnosis": "<primary diagnosis with causal organism if identifiable>",
#   "confidence_level": "High|Medium|Low",
#   "treatment_recommendations": [
#     "<actionable step 1>",
#     "<actionable step 2>",
#     "<actionable step 3>"
#   ],
#   "cited_claims": [
#     {"claim": "<specific factual claim>", "source_indices": [0]},
#     {"claim": "<another claim>",          "source_indices": [1, 2]}
#   ],
#   "follow_up_actions": [
#     "<monitoring or lab action>",
#     "<preventive measure>"
#   ]
# }"""


# # ── Prompt Builder ─────────────────────────────────────────────────────────────

# def _build_user_prompt(
#     caption:          str,
#     retrieved_chunks: list[RetrievedChunk],
#     query_lat:        float,
#     query_lon:        float,
#     query_date:       str,
#     crop_type:        Optional[str],
# ) -> str:
#     """
#     Constructs the user-turn message with full context injection.
#     Each retrieved passage is clearly delimited with its source index,
#     geo-temporal weights, and provenance metadata.
#     """
#     context_blocks: list[str] = []
#     for i, chunk in enumerate(retrieved_chunks):
#         geo_str  = f"{chunk.latitude:.4f}°, {chunk.longitude:.4f}°" if chunk.latitude else "unknown"
#         date_str = chunk.publication_date or "undated"
#         block = (
#             f"[Source {i}] — {chunk.title}\n"
#             f"Source: {chunk.source} | Location: {geo_str} | Date: {date_str}\n"
#             f"Geo-weight: {chunk.geo_weight:.3f} | Temporal-weight: {chunk.temporal_weight:.3f} | "
#             f"Final relevance score: {chunk.final_score:.4f}\n"
#             f"---\n"
#             f"{chunk.content}"
#         )
#         context_blocks.append(block)

#     context_section = "\n\n".join(context_blocks)
#     crop_line       = f"Crop type (user-specified): {crop_type}\n" if crop_type else ""

#     return (
#         f"VISUAL DESCRIPTION (from BLIP-2 image captioning model):\n{caption}\n\n"
#         f"OBSERVATION CONTEXT:\n"
#         f"{crop_line}"
#         f"GPS location: {query_lat:.4f}°N, {query_lon:.4f}°E\n"
#         f"Date observed: {query_date}\n\n"
#         f"RETRIEVED KNOWLEDGE BASE PASSAGES ({len(retrieved_chunks)} sources):\n\n"
#         f"{context_section}\n\n"
#         f"Generate the agricultural advisory report JSON."
#     )


# # ── Main Synthesis Function ────────────────────────────────────────────────────

# def synthesize_advisory(
#     caption:          str,
#     retrieved_chunks: list[RetrievedChunk],
#     query_lat:        float,
#     query_lon:        float,
#     query_date:       str,
#     crop_type:        Optional[str]     = None,
#     client:           Optional[anthropic.Anthropic] = None,
# ) -> AdvisoryReport:
#     """
#     Sends the grounded prompt to Claude and parses the structured JSON response.

#     Includes robust JSON extraction to handle edge cases where the model
#     wraps output in markdown fences despite instructions.
#     """
#     if client is None:
#         client = anthropic.Anthropic()   # Reads ANTHROPIC_API_KEY from environment

#     user_prompt = _build_user_prompt(
#         caption, retrieved_chunks, query_lat, query_lon, query_date, crop_type
#     )

#     response = client.messages.create(
#         model    = CLAUDE_MODEL,
#         max_tokens = MAX_TOKENS,
#         system   = SYSTEM_PROMPT,
#         messages = [{"role": "user", "content": user_prompt}],
#     )

#     raw_text = response.content[0].text.strip()

#     # Robust JSON extraction: strip markdown fences if present
#     if "```json" in raw_text:
#         raw_text = raw_text.split("```json")[1].split("```")[0].strip()
#     elif "```" in raw_text:
#         raw_text = raw_text.split("```")[1].split("```")[0].strip()

#     try:
#         parsed = json.loads(raw_text)
#     except json.JSONDecodeError as e:
#         # Fallback: return a minimal valid report with the error noted
#         return AdvisoryReport(
#             caption                   = caption,
#             summary                   = "Parse error — see diagnosis.",
#             diagnosis                 = f"JSON parsing failed: {e}. Raw output: {raw_text[:500]}",
#             treatment_recommendations = [],
#             cited_claims              = [],
#             confidence_level          = "Low",
#             follow_up_actions         = ["Retry analysis or check model output format."],
#             raw_sources               = retrieved_chunks,
#         )

#     cited_claims = [
#         CitedClaim(
#             claim          = c.get("claim", ""),
#             source_indices = c.get("source_indices", []),
#         )
#         for c in parsed.get("cited_claims", [])
#     ]

#     return AdvisoryReport(
#         caption                   = caption,
#         summary                   = parsed.get("summary", ""),
#         diagnosis                 = parsed.get("diagnosis", ""),
#         treatment_recommendations = parsed.get("treatment_recommendations", []),
#         cited_claims              = cited_claims,
#         confidence_level          = parsed.get("confidence_level", "Low"),
#         follow_up_actions         = parsed.get("follow_up_actions", []),
#         raw_sources               = retrieved_chunks,
#     )

### with Gemini API Key -
"""
LLM Synthesis — Grounded Agricultural Advisory Generation (Powered by Gemini)
"""

import json
import os
from dataclasses import dataclass
from typing import Optional

import google.generativeai as genai
from retrieval import RetrievedChunk

GEMINI_MODEL = "models/gemini-flash-lite-latest"

# ── Output Data Models ─────────────────────────────────────────────────────────
@dataclass
class CitedClaim:
    claim:          str
    source_indices: list[int]

@dataclass
class AdvisoryReport:
    caption:                  str
    summary:                  str
    diagnosis:                str
    treatment_recommendations: list[str]
    cited_claims:             list[CitedClaim]
    confidence_level:         str
    follow_up_actions:        list[str]
    raw_sources:              list[RetrievedChunk]

# ── System Prompt ──────────────────────────────────────────────────────────────
SYSTEM_PROMPT = """You are an expert agricultural plant pathologist and certified agronomist.
You will receive:
  1. A visual description of a crop image.
  2. Retrieved knowledge base passages, each labelled [Source N].
  3. GPS location and observation date context.

Your task is to generate a structured JSON advisory report.

STRICT GROUNDING RULES:
  - Every factual claim in diagnosis or treatment MUST cite at least one source index.
  - Do NOT introduce any information not present in the retrieved passages.
  - If the retrieved evidence is insufficient for a high-confidence diagnosis,
    set confidence_level to 'Low' and state the limitation clearly.
  - source_indices must be valid 0-based integers from the provided context.

OUTPUT FORMAT MUST MATCH THIS JSON SCHEMA EXACTLY:
{
  "summary": "<one sentence overview>",
  "diagnosis": "<primary diagnosis>",
  "confidence_level": "High|Medium|Low",
  "treatment_recommendations": ["<actionable step 1>"],
  "cited_claims": [{"claim": "<specific factual claim>", "source_indices": [0]}],
  "follow_up_actions": ["<monitoring or lab action>"]
}"""

def _build_user_prompt(caption, retrieved_chunks, query_lat, query_lon, query_date, crop_type):
    context_blocks = []
    for i, chunk in enumerate(retrieved_chunks):
        geo_str  = f"{chunk.latitude:.4f}°, {chunk.longitude:.4f}°" if chunk.latitude else "unknown"
        date_str = chunk.publication_date or "undated"
        block = (
            f"[Source {i}] — {chunk.title}\n"
            f"Source: {chunk.source} | Location: {geo_str} | Date: {date_str}\n"
            f"---\n{chunk.content}"
        )
        context_blocks.append(block)

    context_section = "\n\n".join(context_blocks)
    crop_line = f"Crop type (user-specified): {crop_type}\n" if crop_type else ""

    return (
        f"VISUAL DESCRIPTION:\n{caption}\n\n"
        f"OBSERVATION CONTEXT:\n{crop_line}"
        f"GPS location: {query_lat:.4f}°N, {query_lon:.4f}°E\n"
        f"Date observed: {query_date}\n\n"
        f"RETRIEVED KNOWLEDGE BASE PASSAGES:\n\n{context_section}"
    )

def synthesize_advisory(
    caption: str, retrieved_chunks: list, query_lat: float, query_lon: float, 
    query_date: str, crop_type: Optional[str] = None
) -> AdvisoryReport:
    
    genai.configure(api_key=os.environ.get("GEMINI_API_KEY"))
    
    # Using JSON Mode for guaranteed structured output
    model = genai.GenerativeModel(
        model_name=GEMINI_MODEL,
        system_instruction=SYSTEM_PROMPT,
        generation_config={"response_mime_type": "application/json"}
    )

    user_prompt = _build_user_prompt(caption, retrieved_chunks, query_lat, query_lon, query_date, crop_type)
    
    response = model.generate_content(user_prompt)
    
    try:
        parsed = json.loads(response.text)
    except json.JSONDecodeError as e:
        return AdvisoryReport(caption=caption, summary="Parse error", diagnosis=f"Failed: {e}", treatment_recommendations=[], cited_claims=[], confidence_level="Low", follow_up_actions=[], raw_sources=retrieved_chunks)

    cited_claims = [CitedClaim(claim=c.get("claim", ""), source_indices=c.get("source_indices", [])) for c in parsed.get("cited_claims", [])]

    return AdvisoryReport(
        caption=caption, summary=parsed.get("summary", ""), diagnosis=parsed.get("diagnosis", ""),
        treatment_recommendations=parsed.get("treatment_recommendations", []), cited_claims=cited_claims,
        confidence_level=parsed.get("confidence_level", "Low"), follow_up_actions=parsed.get("follow_up_actions", []),
        raw_sources=retrieved_chunks
    )